config/routes.rb
Rentify::Application.routes.draw do
  root :to => "property#index"
  get "/search" => "property#search"
  get "/show/:id" => "property#show", :as => "property"
end

app/models/property.rb
class Property < ActiveRecord::Base
  reverse_geocoded_by :latitude, :longitude

  RANDOM_ADJECTIVES = %w(beautiful nice lovely spacious large cozy unique trendy)
  RANDOM_HOME = %w(home mansion condo lot apartment shack flat house)
  HOME_BASE = { :latitude => 0.0, :longitude => 0.0 }

  attr_accessible :name, :latitude, :longitude, :bedroom_count

  def location
    [self.latitude, self.longitude]
  end

  def self.search(query)
    if query.blank?
      find(:all)
    else
      find(:all, :conditions => ["name LIKE ?", "%#{query}%"])
    end
  end

  # Generates a dummy Property value and saves it to the DB
  def self.generate
    property = Property.new
    property.assign_attributes({
      :name => "#{RANDOM_ADJECTIVES.sample} #{RANDOM_HOME.sample}",
      :bedroom_count => rand(8) + 1,
      :latitude => HOME_BASE[:latitude] + (rand() * 0.1 - 0.05),
      :longitude => HOME_BASE[:longitude] + (rand() * 0.1 - 0.05)
    })
    property.save!
    property
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/property_controller.rb
class PropertyController < ApplicationController
  # GET /
  def index
    @properties = Property.all
    render 'index'
  end

  # POST /search
  def search
    @properties = Property.search(params[:q])
    render 'index'
  end

  # GET /show/:id
  def show
    @property = Property.find_by_id(params[:id])
    if @property.nil?
      render 'public/404', :status => :not_found
    else
      # Normally I would abstract this logic into the Property.near method
      @nearby_properties = Property.near([@property.latitude, @property.longitude], 20, :units => :km)
      @nearby_properties.reject! { |p| p == @property }
      @nearby_properties.sort! { |a, b| Geocoder::Calculations.distance_between(a.location, @property.location) <=> Geocoder::Calculations.distance_between(b.location, @property.location)}
      render 'show'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/property_helper.rb
module PropertyHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rentify</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">Rentify - Demo App </a></h1>
    </li>
  </ul>
</nav>

<%= yield %>

</body>
</html>

app/views/property/index.html.erb
Hey there!

app/views/property/show.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1><%= @property.name %></h1>
    <h4>Located at <%= @property.latitude %>, <%= @property.longitude %></h4>
    <img src="http://placehold.it/950x400" />
  </div>
</div>

<% unless @nearby_properties.blank? %>
  <div class="row">
    <div class="small-12 columns">
      <h2 class="subheader">Nearby properties...</h2>
    </div>
  </div>
  <% @nearby_properties.each do |property| %>
    <br/>
    <div class="row">
      <div class="small-5 columns">
        <img src="http://placehold.it/350x250" />
      </div>

      <div class="small-7 columns">
        <div class="panel">
          <h3><%= truncate(property.name, :length => 30, :seperator => ' ') %></h3>
          <p>This is a great property with <%= pluralize(property.bedroom_count, "bedroom") %>. </p>
          <p>It is located <strong><%= Geocoder::Calculations.distance_between(@property.location, property.location).round(2) %></strong> km away from this property.</p>
          <%= link_to "View this Property", property_path(property), :class => "button" %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

<br/>
<div class="row">
  <div class="small-3 columns">
    <%= link_to "Back", :back, :class => "button" %>
  </div>
  <div class="small-3 columns">
    <%= link_to "Show all Listings", "/", :class => "button" %>
  </div>
</div>